//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ukrlp.SoapApi.Client.ProviderQueryServiceV4 {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProviderQueryPortTypeChannel : Ukrlp.SoapApi.Client.ProviderQueryServiceV4.ProviderQueryPortType, System.ServiceModel.IClientChannel {
    }
}
